spring:
  profiles.active: default

# = Default Profiles
---
# Security
security.user.password: wj

logging.level.org.springframework.security: INFO
spring.thymeleaf.cache: false

spring:
  profiles: default
  profiles.include: app-common,db-common

# Application
server:
  port: 8819

# Datasource
spring.datasource:
  # Connection url for the database "netgloo_blog"
  url: jdbc:mysql://192.168.56.101:3306/springsecurity?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
  # Username and password
  username: root
  password: root

# = Common Profiles
# Application Common
---
spring:
  profiles: app-common
  
#server:
#  display-name: Spring Security

# Database Common
---
spring:
  profiles: db-common

# ===============================
# = DATA SOURCE
# ===============================
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  dbcp.maxActive: 20
  dbcp.max-idle: 8
  dbcp.min-idle: 8
  dbcp.initial-size: 10
  # Keep the connection alive if idle for a long time (needed in production)
  dbcp.testWhileIdle:  true
  dbcp.validationQuery:  SELECT 1


# ====: ==========================
# = JPA / HIBERNATE
# ===============================
spring.jpa:
  # Use spring.jpa.properties.* for Hibernate native properties (the prefix is
  # stripped before adding them to the entity manager).
  # Specify the DBMS
  database: MYSQL
  # Show or not log for each sql query
  show-sql: true

  # Hibernate ddl auto (create, create-drop, update): with "update" the database
  # schema will be automatically updated accordingly to java entities found in
  # the project
  hibernate.ddl-auto: create-drop
#   hibernate.ddl-auto: update
  # Naming strategy
  hibernate.naming.strategy: org.hibernate.cfg.ImprovedNamingStrategy

  # Show or not log for each sql query
  properties.hibernate.show_sql: true

  # Put comments inside all generated SQL statements to hint what\u2019s the generated SQL trying to do
  properties.hibernate.use_sql_comments: true

  # Pretty formatted sql in log
  properties.hibernate.format_sql: true